export const OFFICIAL_PLATFORMS = [
  {
    key: "customer",
    name: "Ride Bangla",
    name_bn: "Ride Bangla",
    description: "Customer platform for accessing Ride Bangla services.",
    description_bn: "Ride Bangla সেবা ব্যবহারের জন্য গ্রাহক প্ল্যাটফর্ম।",
    url: "https://customer.ridebangla.bd",
  },
  {
    key: "partner",
    name: "Ride Bangla Partner",
    name_bn: "Ride Bangla পার্টনার",
    description: "Business and merchant platform for Ride Bangla partners.",
    description_bn: "Ride Bangla পার্টনারদের জন্য ব্যবসা ও মার্চেন্ট প্ল্যাটফর্ম।",
    url: "https://partner.ridebangla.bd",
  },
  {
    key: "rider",
    name: "Ride Bangla Rider",
    name_bn: "Ride Bangla রাইডার",
    description: "Operational platform for registered Ride Bangla riders.",
    description_bn: "নিবন্ধিত Ride Bangla রাইডারদের জন্য অপারেশনাল প্ল্যাটফর্ম।",
    url: "https://rider.ridebangla.bd",
  },
  {
    key: "agent",
    name: "Ride Bangla Agent",
    name_bn: "Ride Bangla এজেন্ট",
    description: "Official platform for the Ride Bangla agent network.",
    description_bn: "Ride Bangla এজেন্ট নেটওয়ার্কের অফিসিয়াল প্ল্যাটফর্ম।",
    url: "https://agent.ridebangla.bd",
  },
  {
    key: "it",
    name: "Ride Bangla IT",
    name_bn: "Ride Bangla IT",
    description: "Professional app, website, graphics and digital development services.",
    description_bn: "পেশাদার অ্যাপ, ওয়েবসাইট, গ্রাফিক্স ও ডিজিটাল ডেভেলপমেন্ট সেবা।",
    url: "https://it.ridebangla.bd",
  },
] as const;
